services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movie-db
      MYSQL_USER: moviedb
      MYSQL_PASSWORD: 1234
    volumes:
      - movie-db:/var/lib/mysql
    ports:
      - 3306:3306
  myadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 9000:80
volumes:
  movie-db:
