services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: moviedb
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db
      - configdb-volume:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: movie
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    ports:
      - 8081:8081
volumes:
  db-volume:
  configdb-volume: